resilience4j:
  circuitbreaker:
    configs:
      defecto:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products:
        base-config: defecto
  timelimiter:
    configs:
      defecto:
        timeout-duration: 4s
    instances:
      products:
        base-config: defecto
spring:
  cloud:
    gateway:
      routes:
      - id: msvc-products
        uri: lb://msvc-products
        predicates:
        - Path=/api/products/**
        # - Header=token, 12345
        # - Method=GET,POST
        # - Query=color, verde
        # - Cookie=color, azul
        # - Header=Content-Type, application/json
        filters:
        - name: CircuitBreaker
          args:
            name: products
            statusCodes: 500, 404
            fallbackUri: forward:/api/items/5 # Redireccion hacia pagina mensaje ?
        - StripPrefix=2
        - EjemploCookie=Hola llaunas !!!, user, David
      - id: msvc-items
        uri: lb://msvc-items
        predicates:
        - Path=/api/items/**
        filters:
          - StripPrefix=2
          - AddRequestHeader=token-request, llaunas
          - AddResponseHeader=token-response, 98765432
          - AddRequestParameter=name, David